GET http://localhost:3000/todos/
###

GET http://localhost:3000/todos/:todoId/
###

GET http://localhost:3000/agenda/
###

GET http://localhost:3000/todos/?category=HOME
###

GET http://localhost:3000/todos/?category=LEARNING&priority=HIGH
###

GET http://localhost:3000/todos/?priority=AVERAGE

###
POST http://localhost:3000/todos/
Content-Type: application/json

{
 "id": 6,
 "todo": "Finalize event theme",
 "priority": "LOW",
 "status": "TO DO",
 "category": "HOME",
 "dueDate": "2021-02-22"
}

